### PR TITLE
remove the session lock error message, includes contaria's changes

### PR DESCRIPTION
**Pull request by tildejustin**

### CODE REVIEW

**Comment by jan-leila** [comment]
whats the idea with using an atomic here? atomics only lock for the value itself, dont we want to block for the entire time saving is still happening and not just the check for if its happeneing?

**Comment by tildejustin** [comment]
https://discord.com/channels/928728732376649768/928730156967788645/1038408521550675978 this discussion seems to be the impetus for it, I didn't write that part so I don't really know

**Comment by jan-leila** [comment]
oh wait i see i thought the outer layer of the sync was also replaced with their one atomic but its not good then

**Comment by jan-leila** [comment]
thoughts on setting up CICD, closing this pr and then we just fork yours to mcsr repo?

**Comment by tildejustin** [comment]
works for me, I can push the CICD stuff but you'll have to make the org repo

**Comment by tildejustin** [comment]
pushed

**Pull request closed without merging**
